version: 4.0.2.{build}
image: Visual Studio 2017
branches:
  only:
    - master
    - develop
build_script:
  - build.cmd --target=build --configuration=Release
  - build.cmd --target=test --configuration=Release
  - build.cmd --target=pack --configuration=Release 
test: off
deploy: off 
artifacts:
  - path: 'artifacts\unit-tests.xml'
  - path: 'packages\*.nupkg'